### PR TITLE
faq: How to produce log messages from an api.js module

### PR DESCRIPTION
**Pull request by rpl**

### CODE REVIEW

**Comment by rpl** [comment]
@kewisch can you take a brief look at this additional faq entry?
Thanks!

Side note: we should probably add the suggested snippet into the experiment boilerplate repo (https://github.com/web-ext-experiments/boilerplate-experiment) because being able to produce `console.log` messages while you are working on the experiment implementation is definitely more helpful than using `dump` in many ways (e.g. to be able to inspect an object that cannot be serialized into a string, filter the log messages easily as the Browser Console already support, etc.).

**Comment by kewisch** [comment]
Text and code looks good to me, but maybe instead we can fix this by making the ConsoleAPI to all WebExtensions experiments by making the object available through the sandbox?

**Comment by rpl** [comment]
@kewisch I definitely agree that it would be way better if we make it available in the experiment sandbox without the need to import the ConsoleAPI JSM module and then create the instance manually.

Filed as [Bug 1351381 - Provide a console API object in experiments API sandbox](https://bugzilla.mozilla.org/show_bug.cgi?id=1351381) (and proposed patch attached to it).

**Comment by rpl** [comment]
Updated to reflect the change just landed in Firefox 55 (where the console object is now already available in the api.js sandbox environment).

**Comment by andymckay** [comment]
Thanks @rpl sorry I missed this.

**Pull request merged**
